services:
  - type: web
    name: quran-ai-bot
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false