services:
  - type: web
    name: quran-ai-bot
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK
        value: "true"
      - key: WEBHOOK_URL
        value: https://quran-ai-bot.onrender.com
      - key: WEBHOOK_SECRET
        sync: false
      - key: SELF_URL
        value: https://quran-ai-bot.onrender.com